HOSTS:
  el7:
    roles:
      - server
      - default
      - master
    platform:   el-7-x86_64
    image:      rhel-7-v20170426
    hypervisor: google
  el6:
    roles:
      - client
    platform:   el-6-x86_64
    image:      rhel-6-v20170426
    hypervisor: google
    ssh:
      keepalive: true
      keepalive_interval: 1
      host_key:
        - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:host_key].join("\n#{' '*8}- ") %>
      kex:
        - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:kex].join("\n#{' '*8}- ") %>
      encryption:
        - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:encryption].join("\n#{' '*8}- ") %>
      hmac:
        - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:hmac].join("\n#{' '*8}- ") %>
CONFIG:
  log_level: verbose
  type:      aio
  keyfile:  ADD_ME
  gce_project: ADD_ME
  gce_keyfile: ADD_ME
  gce_email: ADD_ME
